### ISSUE TITLE
Use MAVLink messages when IP network is not available

### ISSUE THREAD

**Issue by anselmolsm** [01org/camera-streaming-daemon#12]
Currently the daemon streams video assuming there is a cabled or WiFi network. However, especially thinking about UAVs, the vehicle might be outside the range of WiFi. To cover such scenario, a possible way to continue controlling the daemon is through MAVLink messages over RF.

**Comment by lucasdemarchi** [comment]
No. The video should never be sent over mavlink. Control messages can though, like for start/stop recording, taking still photos, etc

**Comment by anselmolsm** [comment]
Text updated. Thanks. BTW, I think you can edit that as well.
