### ISSUE TITLE
README: fix run command (it's "csd" not "camera-streaming-daemon" right?)

### ISSUE THREAD

**Issue by rmackay9** [01org/camera-streaming-daemon#44]
In the README file's "Running" section it says that to run the program, "camera-streaming-daemon" should be typed but it's been shortened at some point to just "csd" hasn't it?

I'm not totally sure..

**Comment by lucasdemarchi** [comment]
Yep, can you send a patch?

**Comment by rmackay9** [comment]
Sure, PR'd here: https://github.com/01org/camera-streaming-daemon/pull/46
