### ISSUE TITLE
Does Poky Aero (Intel Aero Linux Distro) 1.4.0-dev (pyro) contain all the dependencies?

### ISSUE THREAD

**Issue by cnpcshangbo** [01org/camera-streaming-daemon#67]
From this page (https://github.com/01org/camera-streaming-daemon/wiki/Deploying-on-Aero), it was said we need to build an updated Aero image to run this daemon. From yesterday, we can download the Aero1.4 dev image from https://download.01.org/aero/images/. I wonder if this image is going to work.

I tried to run `scd` on Poky Aero (Intel Aero Linux Distro) 1.4.0-dev (pyro) and I got these message:
```
root@intel-aero:~# csd

(csd:723): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(csd:723): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(csd:723): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Unable to start rtsp server
AVAHI START
```
I wonder if I still need to build the image or I missed something to run `csd`?
Thanks,
Bo

**Comment by anselmolsm** [comment]
Hi @cnpcshangbo 

1.4-rc2 already had the daemon, but I suggest you to try with 1.4 [we've just released](https://github.com/intel-aero/meta-intel-aero/releases/tag/v1.4). The image is on its way to become available for download from downloadcenter.intel.com.

csd daemon is enabled to be executed by systemd as part of the boot, so you should not need to run it manually.

**Comment by cnpcshangbo** [comment]
We finally flashed to 1.4 version and the `csd` does run automatically as you mentioned. So this issue is solved. Thanks.
