### ISSUE TITLE
Which Qt version should I use to build the customized QGroundControl?

### ISSUE THREAD

**Issue by cnpcshangbo** [01org/camera-streaming-daemon#70]
We tried to follow this tutorial (http://qgroundcontrol.org/dev/build_qgc_new#b_linuxmac_os_xgnu) to build QGC, however, we continuous receive messages saying "Project ERROR: Unsupported Qt version, 5.5+ is required", even if we install Qt 5.7.1 or Qt 5.9. 
![571](https://user-images.githubusercontent.com/4831029/28045790-26066126-6594-11e7-882f-45b9ac4a5e80.png)
![571 version](https://user-images.githubusercontent.com/4831029/28045802-3486f31e-6594-11e7-8fd5-5957c485fbef.png)
![qt version problem](https://user-images.githubusercontent.com/4831029/28045832-71b67872-6594-11e7-9c3e-05d4c3c74e84.png)

I wonder if it is something wrong with my Qt configuration or I need a specific Qt version?
Do I need to build Qt from source code?
Thanks,
Bo

**Comment by lucasdemarchi** [comment]
This is something to ask on the QGC gitter/github/etc.
