### ISSUE TITLE
Unable to Select the Desired Video Stream and Resolution

### ISSUE THREAD

**Issue by aho38** [01org/camera-streaming-daemon#75]
![screenshot from 2017-07-25 11-13-55](https://user-images.githubusercontent.com/30444257/28587212-31988ae4-712b-11e7-9eb3-f0ba145fc6e5.png)

After building it (MAVLink Advertisement QGoundControl), I am unable to select the desired video stream and resolution within Widget > Video Stream. Please help!

**Comment by anselmolsm** [comment]
@aho38 Please share info about the version of CSD running in the drone you're connecting to. Is that Intel Aero? If so, Camera Streaming Daemon shipped in the image has mavlink support disabled, but you can rebuild that modifying the configure parameter --enable-mavlink .

**Comment by aho38** [comment]
Yes, it is Intel Aero v1.4. I'm following @cnpcshangbo 's work.
