### ISSUE TITLE
Question: handle_mavlink_message

### ISSUE THREAD

**Issue by aho38** [01org/camera-streaming-daemon#76]
![screenshot from 2017-07-26 15-39-37](https://user-images.githubusercontent.com/30444257/28646821-80e50904-7218-11e7-8416-f95dcf80668f.png)

We are currently using V1.4. However we did not get "Camera Daemon found: sysid: %d" message.

**Comment by lfelipe** [comment]
@aho38, the binary shipped with 1.4 does not have mavlink enabled by default, as that implementation is still being discussed and worked on within the Dronecode community.
