### ISSUE TITLE
avahi-qt4 development package not found

### ISSUE THREAD

**Issue by aho38** [01org/camera-streaming-daemon#77]
![screenshot from 2017-07-27 16-21-58](https://user-images.githubusercontent.com/30444257/28695988-8aab7d90-72e7-11e7-98cd-1897d9aeb986.png)
Where or how can I compile avahi-qt4?
I did a little research can't seem to find a straight up answer for my question.
I found this issue from other people and tried to follow the pattern hoping to find similarities in my issue and his.
https://forums.gentoo.org/viewtopic-t-520646.html

**Comment by anselmolsm** [comment]
If it's Ubuntu, try: apt-get install libavahi-qt4-dev.
Give that a try, but notice that is not directly related to CSD project.
