### ISSUE TITLE
MAVLink protocol/PX4 code examples 

### ISSUE THREAD

**Issue by RohanKurane** [01org/camera-streaming-daemon#81]
Hi,
This is more of an inquiry. Are there any MAVLink protocol/PX4 code examples that I can look at and use in my application to talk to the flight controller and sensors on the drone ? Any documentation will help go a long way. 

Please close this issue as soon as you can provide the information. If there is a better way to ask this , let me know for future reference. 

@lucasdemarchi @zehortigoza 

Thanks
Rohan

**Comment by zehortigoza** [comment]
Here some examples in python and C++.
https://github.com/01org/mavlink-router/tree/master/examples
