### ISSUE TITLE
Add more encoders

### ISSUE THREAD

**Issue by lucasdemarchi** [01org/camera-streaming-daemon#84]
From @fnoop's comment: https://github.com/01org/camera-streaming-daemon/issues/82#issuecomment-323184017

> Possibly the main reason you'll see this is because the stream requires quite a
> high bitrate because csd hard codes the pipeline construction to compress and transmit each frame using jpg, rather than a video codec like h264. 
> [...]
> CSD should add more encoder options, in particular h264/h265/vp[89] etc

**Comment by zehortigoza** [comment]
This is a duplicated of https://github.com/01org/camera-streaming-daemon/issues/56
